package view;

import java.awt.Color;
import javax.swing.JOptionPane;


public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnCliente = new javax.swing.JMenu();
        btnClienteCadastro = new javax.swing.JMenuItem();
        btnProduto = new javax.swing.JMenu();
        btnProdutoCadastro = new javax.swing.JMenuItem();
        btnVenda = new javax.swing.JMenu();
        btnVendaRealizarVenda = new javax.swing.JMenuItem();
        btnVendaInformaçoes = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenu();
        btnSairEncerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cliente_1.png"))); // NOI18N
        btnCliente.setText("Clientes");
        btnCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteMouseEntered(evt);
            }
        });

        btnClienteCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        btnClienteCadastro.setText("Cadastrar Cliente");
        btnClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteCadastroActionPerformed(evt);
            }
        });
        btnCliente.add(btnClienteCadastro);

        jMenuBar1.add(btnCliente);

        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/produtos_1.png"))); // NOI18N
        btnProduto.setText("Produtos");
        btnProduto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutoMouseEntered(evt);
            }
        });

        btnProdutoCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        btnProdutoCadastro.setText("Cadastrar Produto");
        btnProdutoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoCadastroActionPerformed(evt);
            }
        });
        btnProduto.add(btnProdutoCadastro);

        jMenuBar1.add(btnProduto);

        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/venda.png"))); // NOI18N
        btnVenda.setText("Vendas");
        btnVenda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVendaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVendaMouseEntered(evt);
            }
        });

        btnVendaRealizarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        btnVendaRealizarVenda.setText("Realizar Venda");
        btnVendaRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaRealizarVendaActionPerformed(evt);
            }
        });
        btnVenda.add(btnVendaRealizarVenda);

        btnVendaInformaçoes.setText("Consultar Vendas");
        btnVendaInformaçoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaInformaçoesActionPerformed(evt);
            }
        });
        btnVenda.add(btnVendaInformaçoes);

        jMenuBar1.add(btnVenda);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
        });

        btnSairEncerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnSairEncerrar.setText("Sair do Sistema PDV");
        btnSairEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairEncerrarActionPerformed(evt);
            }
        });
        btnSair.add(btnSairEncerrar);

        jMenuBar1.add(btnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteCadastroActionPerformed
        // Abrir tela de cadastro de clientes
        FormCliente form = new FormCliente();
        form.setVisible(true);
    }//GEN-LAST:event_btnClienteCadastroActionPerformed

    private void btnProdutoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoCadastroActionPerformed
        // Abrir tela de cadastro de produtos
        FormProduto form = new FormProduto();
        form.setVisible(true);
    }//GEN-LAST:event_btnProdutoCadastroActionPerformed

    private void btnVendaRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaRealizarVendaActionPerformed
        // Abrir tela de venda de produtos
        FormVenda form = new FormVenda();
        form.setVisible(true);
    }//GEN-LAST:event_btnVendaRealizarVendaActionPerformed

    private void btnSairEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairEncerrarActionPerformed
        // Sair do sistema
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja sair do sistema?", "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairEncerrarActionPerformed

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
        // Personalizando menu de cliente ao interagir com mouse
        btnCliente.setForeground(Color.ORANGE);
    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseExited
        // Personalizando menu de cliente ao tirar o mouse
        btnCliente.setForeground(null);
    }//GEN-LAST:event_btnClienteMouseExited

    private void btnProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoMouseEntered
        // Personalizando menu de produto ao interagir com mouse
        btnProduto.setForeground(Color.ORANGE);
    }//GEN-LAST:event_btnProdutoMouseEntered

    private void btnProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoMouseExited
        // Personalizando menu de produto ao tirar o mouse
        btnProduto.setForeground(null);
    }//GEN-LAST:event_btnProdutoMouseExited

    private void btnVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseEntered
        // Personalizando menu de venda ao interagir com mouse
        btnVenda.setForeground(Color.ORANGE);
    }//GEN-LAST:event_btnVendaMouseEntered

    private void btnVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVendaMouseExited
        // Personalizando menu de venda ao tirar o mouse
        btnVenda.setForeground(null);
    }//GEN-LAST:event_btnVendaMouseExited

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        // Personalizando menu de sair ao interagir com mouse
        btnSair.setForeground(Color.RED);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        // Personalizando menu de sair ao tirar o mouse
        btnSair.setForeground(null);
    }//GEN-LAST:event_btnSairMouseExited

    private void btnVendaInformaçoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaInformaçoesActionPerformed
        // Detalhes sobre as vendas
        FormVendaDados venda = new FormVendaDados();
        venda.setVisible(true);
    }//GEN-LAST:event_btnVendaInformaçoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnCliente;
    private javax.swing.JMenuItem btnClienteCadastro;
    private javax.swing.JMenu btnProduto;
    private javax.swing.JMenuItem btnProdutoCadastro;
    private javax.swing.JMenu btnSair;
    private javax.swing.JMenuItem btnSairEncerrar;
    private javax.swing.JMenu btnVenda;
    private javax.swing.JMenuItem btnVendaInformaçoes;
    private javax.swing.JMenuItem btnVendaRealizarVenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
